### ISSUE TITLE
Set-env is deprecated

### ISSUE THREAD

**Issue by KTibow** [github/ossar-action#16]
To quote GitHub Actions:
The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by thomasplevy** [comment]
+1 here, I'm getting a ton of failing builds now and I can't figure out if there's something I can do on my end to fix this

**Comment by timoludwig** [comment]
Same here, I ended up temporarily disabling the entire workflow.

**Comment by davidknise** [comment]
Acknowledged. Working on a fix. Estimated time is by end of day.

**Comment by thomasplevy** [comment]
@davidknise thanks so much <3

**Comment by davidknise** [comment]
@actions/core has been updated to v1.2.6 in the master and v1 branches, which fixes the core.exportVariable function used by this build task. Please retrigger your workflows to confirm the fix.

**Comment by thomasplevy** [comment]
@davidknise looks good thank you so much!

**Comment by KTibow** [comment]
Can you close for me? (Not able to access the GitHub web interface right now, just email.)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by KTibow** [comment]
LGTM!

**Comment by davidknise** [comment]
Thank you all for reporting the issue. I'll setup a better daily canary workflow and figure out why I haven't been getting GitHub notifications.
