### ISSUE TITLE
It's unclear what languages are covered

### ISSUE THREAD

**Issue by rugk** [github/ossar-action#22]
https://github.com/github/ossar-action#open-source-tools lists the tools and some languages.

However, that is hard to find and you need to click-through. Also is the shown language there the one the test tool is written in or the language iut can test? This is not made clear in the doc…

**Comment by davidknise** [comment]
> that is hard to find
As the table is on the home readme, I don't think it can get much more discoverable.

> Also is the shown language there the one the test tool is written in or the language iut can test
Language it can test.

> This is not made clear in the doc…
I'll add a line of text above that table that clarifies that the table is the list of current available open source tools and the languages that each tool can analyze.

**Comment by davidknise** [comment]
The `README.MD` section you linked has been updated with further clarification.

**Comment by rugk** [comment]
Okay thanks (though it's rather the bottom of the Readme… :upside_down_face:)

**Comment by jamesylgan** [comment]
@davidknise ESLint allows configuration for extra filetypes e.g. `ecmaFeatures: { jsx: true }` https://stackoverflow.com/questions/36188569/configuring-eslint-with-jsx

Possible to add this to OSSAR?
