### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by srivatsamarichi** [github/ossar-action#3]
Hi, 

I got this error during my workflow run for **OSSAR Analysis** when I executed for my **Spring boot App**. Can someone help me here, please?

**DirectoryNotFoundException:** Could not find a part of the path 'd:\a\_msca\versions\temp'.

![ossar-analysis-error](https://user-images.githubusercontent.com/13433045/86884482-3f5ebe80-c111-11ea-8f68-5e1b704291bc.png)

**Additional details**

**Workflow run** - https://github.com/srivatsamarichi/spring-petclinic/runs/848560395?check_suite_focus=true

**Comment by boAndron** [comment]
Hey Srivatsa,
This was a bug introduced in the last version. We've already got a fix for it, pending review and release.
You can safely mitigate the problem by manually creating the folder 'd:\a_msca\versions\temp'.
Apologies for any inconvenience.
Thanks for reporting!
Cheers,
Bogdan

**Comment by srivatsamarichi** [comment]
Awesome, thanks for the heads up!

**Comment by srivatsamarichi** [comment]
I till have issues running this action. Can you help me?

**Workflow run:** https://github.com/srivatsamarichi/MyShuttle-Java/runs/862887186?check_suite_focus=true

**Comment by boAndron** [comment]
Looks like you don't have any applicable targets to scan. From what I can tell this is a java project, which means there should be applicable targets for at least spotbugs(.jar files), but it looks like you aren't building your project, so unless you've checked them into your repo, there won't be any .jar files for spotbugs. 
Can you try adding a build step before running the OSSAR action and let us know if that helps?
Thanks!

**Comment by srivatsamarichi** [comment]
Let me give it a shot.

**Comment by davidknise** [comment]
Correction from @boAndron, we have not yet released spotbugs.

The OSSAR action doesn't have any tools that are applicable to your codebase, _yet_. We will be introducing more tools, such as SpotBugs (Java) and FlawFinder (C/C++) over the next few weeks.

**[Action Item] The action should not fail when none of the tools are applicable, simply write out an appropriate, non-error message to the console.**

We will push that update this week.

**Comment by srivatsamarichi** [comment]
@davidknise thanks for the heads up. However, is the action currently supported for .netcore? I still face issues when I run it against my .netcore repo.

Here is the workflow run for the same- https://github.com/srivatsamarichi/tailspin-spacegame-web/runs/863809647?check_suite_focus=true

**Comment by boAndron** [comment]
This looks like a known EsLint [issue](https://github.com/github/ossar-action/issues/2). We're working on it. A quick mitigation might be adding a no-op typescript file to your project, but that might trip up eslint in different ways :)

**Comment by srivatsamarichi** [comment]
Any updates?

**Comment by LucasLarson** [comment]
> manually creating the folder 'd:\a_msca\versions\temp'.

So would that be something like https://github.com/username/repo/tree/main/d/a_msca/versions/temp or is this meant to be run offline on Windows machines only?
