### ISSUE TITLE
MSCA being retired

### ISSUE THREAD

**Issue by klane** [github/ossar-action#33]
The note below from the Microsoft Security Code Analysis [documentation](https://docs.microsoft.com/en-us/azure/security/develop/security-code-analysis-overview) indicates that it will be retired. Does that mean this action will cease to function at that time?

![image](https://user-images.githubusercontent.com/4753004/127801197-36a5f85d-90f1-4092-a18f-93f4dc9c75b3.png)

**Comment by davidknise** [comment]
No, the CLI used by this action will not be deprecated. It will likely be renamed from the **Microsoft Security Code Analysis** brand.

The current **MSCA** documentation and deprecation covers our paid **Azure DevOps Extension**.

Sorry for the confusion, and thanks for the great question.

**Comment by davidknise** [comment]
As a follow up, I will update the docs accordingly to remove linked references to MSCA documentation.

**Comment by klane** [comment]
Thanks for the quick response @davidknise.
